"""
Constants for Soviet.
"""


JOB_STATUS_UNSTARTED = 0
JOB_STATUS_STARTED = 1
JOB_STATUS_RUNNING = 2
JOB_STATUS_COMPLETE = 3
JOB_STATUS_FAILED = 4

JOB_STATUS_NAMES = {
	JOB_STATUS_UNSTARTED: u"Unstarted",
	JOB_STATUS_STARTED: u"Started",
	JOB_STATUS_RUNNING: u"Running",
	JOB_STATUS_COMPLETE: u"Complete",
	JOB_STATUS_FAILED: u"Failed",
}
